import Head from 'next/head'
import{BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin, AiFillGithub, AiFillMail} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Megh Pathak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      <main className=' bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-sfpro'>pathakme</h1>
            <ul className=' flex items-center'>
              <li>
                <BsFillMoonStarsFill className=' cursor-pointer text-2xl'/>

              </li>
              <li><a href="#" className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Megh Pathak</h2>
            <h3 className='text-2xl py-2'>Student and Gamer.</h3>
            <p className='text-md py-5 leading-9 text-gray-800'>
              I am a 3rd year Mathematics and Computer Science student at University of Toronto Mississauga. 
              I have great interest in full-stack development, human-computer interactions, designing, gaming and everything in between.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin/>
            <AiFillMail/>
            <AiFillGithub/>
          </div>
        </section>
      </main>

    </div>
  )
}
